spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/pet_shop
spring.datasource.username=petshop_app
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
