spring.application.name=backend

datasource.url=jdbc:mysql://localhost:3306/pet_shop
datasource.username=petshop_app
datasource.password=your_password

jpa.hibernate=
jpa.ddl-auto=validate
jpa.open-in-view=false

flyway.enabled=true
